[project]
name            = 'nya-fmt'
dynamic         = ['version']
description     = 'A reincarnation of tcrutils.fmt_iterable that strives to be less buggy, less crashy (fail gracefully), as well as be more easily extensible and maintainable'
readme          = "README.md"
requires-python = ">=3.12"

dependencies = [ #
	"astpretty>=3.0.0",
	"nya-result>=0.1.4",
	"nya-scope>=0.3.1",
	"rich>=15.0.0",
]

# [project.scripts]
# nya_fmt = "nya_fmt.__main__:main"

[build-system]
requires      = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path    = "src/nya_fmt/_version.py"
pattern = '__version__(?:: str)? *= *\"(?P<version>[^\"]+)\"'

[dependency-groups]
dev = [ #
	"zooo",
	"hikari==2.6.0",
	"mypy==2.3.1",
	"pydantic>=2.13.5",
	"pytest==9.1.1",
	"tcrutils==13.1.39",
	"ty==0.0.83",
]

[tool.uv.sources]
zooo = { path = "/home/anamoyee/proj/PYPACKAGES/zooo", editable = true }
